### ISSUE TITLE
Can't read legit wav file (NonPcmFormatButMissingFact)

### ISSUE THREAD

**Issue by ivxvm** [mrkkrp/wave#11]
https://uploadfiles.io/we5b6
This one works in every single media player and DAW I have.
Yet trying to read it using `readWaveFile` throws `NonPcmFormatButMissingFact`.

**Comment by sboosali** [comment]
i'll take a look at this

**Comment by sboosali** [comment]
audio players and workstations do a broad range of stuff to audio. python can't read the file either:

```
#!/usr/bin/env python

import wave

```

**Comment by sboosali** [comment]
`wave` works with the PCM kind of WAV (`WAVE_FORMAT_PCM`: `0x0001`). your file seems to have kind IEEE Float (`WAVE_FORMAT_IEEE_FLOAT`: `0x0003`)

<https://www.videolan.org/developers/vlc/doc/doxygen/html/vlc__codecs_8h.html>

**Comment by sboosali** [comment]
The docs say:

>You can feed vanilla WAVE and RF64 files. The actual format is detected automatically from the contents of the file, not by extension. 
>PCM with samples in form of integers and floats only are supported, see SampleFormat. 

http://hackage.haskell.org/package/wave-0.2.0/docs/Codec-Audio-Wave.html#v:readWaveFile

My guess is that your audio file is compressed

audio players and workstations can read/write a broad range of audio. for comparison, python can't read the file either:

```
#!/usr/bin/env python

import wave

with wave.open("./tests/issue-11.wav", "rb") as audio:

    print audio.getnframes()

# <<< wave.Error: unknown format: 3 >>>
```

iiuc, the python standard library can only read the integer (pcm) data, while this package can read integer data or float data (but not any of the other kinds of data). so, your audio might be compressed, or be in one of a hundred other formats which a `.wav` file can contain: <https://www.videolan.org/developers/vlc/doc/doxygen/html/vlc__codecs_8h.html>

@mrkkrp correct me if I'm wrong, but `SampleFormat` (i.e. what `wave` can process) corresponds to these two formats supported by `VLC`:

* `WAVE_FORMAT_PCM` (`0x0001`)
* `WAVE_FORMAT_IEEE_FLOAT` (`0x0003`)

**Comment by ivxvm** [comment]
@sboosali 
Thanks for your analysis! Maybe this one can remain open in case anyone wants to implement additional wav types support. As I understand, other formats are unsupported not by design, but because no one managed to implement them yet: https://github.com/mrkkrp/wave#limitations

**Comment by sboosali** [comment]
I'd prefer to keep this closed, then open a specific issue for individual wave formats.

if you find out the format of your `.wav`, let us know (i ran `sox` on it with different options, but I couldn't find in the man page an option like `sox --print-wave-format`).

**Comment by sboosali** [comment]
Relatedly, how did you generate the audio (like what programs, whether or not any options were the defaults.)? I don't know much about audio software, but if several of them all output the same kind of wav format by default, it might be worth prioritize adding support for that format (if it exists). I assume it would be a compressed format that is natively supported by windows, but that is an uninformed guess.

**Comment by ivxvm** [comment]
@sboosali 
Ok, no problem, I'll inform you if I will find out what exactly format this is. I tried to use `wave` to massively process all samples from my collection (free sample packs from internet), and this is how I got this issue. ~70% files are ok, 30% are not working due to this issue, and just few files are not working due to another one (BadFileFormat).
