### ISSUE TITLE
Can't read legit wav file (BadFileFormat)

### ISSUE THREAD

**Issue by ivxvm** [mrkkrp/wave#12]
https://ufile.io/e2gsj
This one works in every single media player and DAW I have.
Yet trying to read it using `readWaveFile` throws `BadFileFormat`:
```
BadFileFormat "Failed reading: Unsupported audio format specified in fmt chunk\nEmpty call stack\n" "D:\\Samples\\Money Kits\\CashMoneyAP - Official Drum Kit Vol. 1\\CashMoneyAp HITS\\CashMoneyAp HIT (3).wav"
```

**Comment by mrkkrp** [comment]
@sboosali Would you be able to look into this? Unfortunately, I myself don't have enough time to dedicate to this.

**Comment by sboosali** [comment]
@mrkkp yes

(sorry, i saw the "Can't read legit wav file (...)" header in my email, and I mistook it for the earlier issue with a similar header, and I just went to the open tab with the issue in my browser.)

**Comment by ivxvm** [comment]
I'm sorry for the confusing title, I wanted to make it similar (except details), to make title and description self-sufficient (but still separate issue).

**Comment by sboosali** [comment]
(@ivxvm no i think your titles were good, i was just busy and skimmed. :-) )

like #11 , this seems to be a non-PCM-formatted (or Float-formatted) WAV.

again, neither python's standard library nor this package can read the file either, but sox can.

`sox`:

```
$ play tests/issue-12.wav 
...

$ play --version
play:      SoX v14.4.2
```

`python`:

```
#!/usr/bin/env python

import wave

wave.open("./tests/issue-12.wav", "rb")

# <<< wave.Error: unknown format: 2 >>>
```

i.e. a WAV of type "Adaptive Differential PCM" (`WAVE_FORMAT_ADPCM: 0x0002` in <https://www.videolan.org/developers/vlc/doc/doxygen/html/vlc__codecs_8h.html#a6db17b7eb578674222f7629e38aa444c>)

(note that `play` could read the audio file in #11 too, like your audio player / DAW, besides it can read many WAV formats).

**Comment by sboosali** [comment]
@ivxvm btw, you can convert all your `.wav`s files to the WAV Format which `wave` can parse with `sox` (either `signed-integer` or `unsigned-integer` encodings work):

```
$ function convert-any-wav-to-pcm-wav { sox  --type wav "$1"   --type wav --encoding signed-integer "pcm_$1.wav"; }

$ convert-any-wav-to-pcm-wav ./issue-12.wav
```

`F.P. PCM` audio:

```
$ play issue-11.wav 

issue-11.wav:

 File Size: 2.12M     Bit Rate: 2.82M
  Encoding: F.P. PCM      
  Channels: 2 @ 25-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: 00:00:06.00  

```

`MS ADPCM` audio:

```
$ play issue-12.wav 

issue-12.wav:

 File Size: 43.1k     Bit Rate: 356k
  Encoding: MS ADPCM      
  Channels: 2 @ 14-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: 00:00:00.97  

In:100%  00:00:00.97 [00:00:00.00] Out:42.8k [      |      ] Hd:4.1 Clip:0    
```

`Signed PCM` audio:

```
$ sox   --type wav ./issue-12.wav   --type wav --encoding signed-integer ./issue-12.wav.pcm

$ play issue-12.wav.pcm

issue-12.wav.pcm:

 File Size: 171k      Bit Rate: 1.41M
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: 00:00:00.97  
```

`Unsigned PCM` audio:

```
$ sox   --type wav ./issue-11.wav   --type wav --encoding unsigned-integer ./issue-11.wav.pcm

$ play issue-11.wav.pcm

./issue-11.wav.pcm:

 File Size: 529k      Bit Rate: 706k
  Encoding: Unsigned PCM  
  Channels: 2 @ 8-bit    
Samplerate: 44100Hz      
Replaygain: off         
  Duration: 00:00:06.00  
```

**Comment by sboosali** [comment]
(Closing for reason of unsupported WAV Format, like #11)
