### ISSUE TITLE
Misleading Documentation?

### ISSUE THREAD

**Issue by freckletonj** [mrkkrp/wave#16]
Thank you for this lib, the community desperately needs good audio libraries, and your code is very well written.

It seems I'm not the only one who thought this read in actual bytes of a WAV, and your readme seems to imply it should:

> This module provides a safe interface that allows to manipulate WAVE files
> It suffices to say that they read samples of audio stream and put them into a linked list
> This wave package is the first serious solution

Perhaps a comment that this allows a user to work with _metadata_ would clear up confusion.

Also, I'm new to manipulating audio files in code, so an example would be great. I tried reading through your LAME and FLAC libs, but there's some indirection, and the FFI to C libs is throwing me off, and I'd just like to get the bytes of audio into memory without needing to learn how waves are structured. Any chance for a helper fn, or an example?

Thanks again! Glad I found this lib :D

**Comment by mrkkrp** [comment]
Use `readWaveFileSource` to get the `Wave` record with the metadata. Note the useful fields `waveDataOffset`, `waveDataSize`, and `waveSamplesTotal`. This is all you need to load an audio stream into memory. Just open a file, skip first `waveDataOffset` bytes and then you will have `waveDataSize` bytes of audio data. This is what I do in LAME and FLAC, perhaps in C (I don't really remember), but it doesn't mean you can't do the same in Haskell.

**Comment by freckletonj** [comment]
Oof, I was making it harder than I needed to. Thank you, that worked great!
