### ISSUE TITLE
volunteering to be a co-mainter for `wave`

### ISSUE THREAD

**Issue by sboosali** [mrkkrp/wave#5]
idk about qualifications, but I've been writing several dictation related packages, so at the least, I will be working with `WAVE` files, and using this package, for the next several years.

responding to: https://www.reddit.com/r/haskell/comments/9g00oj/looking_for_comaintainers_for_my_opensource/

**Comment by sboosali** [comment]
package username is `sboo`

(https://hackage.haskell.org/user/sboo )

**Comment by mrkkrp** [comment]
OK, I added you on Hackage as well. Thanks for your interest!

**Comment by sboosali** [comment]
Sweet!

i'll take a look at the code this weekend.
